language: node_js
skip_cleanup: true
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - echo "Deploying to firebase hosting"
  - firebase deploy --project cryptus-dff89 --token $FIREBASE_TOKEN
